### ISSUE TITLE
Tagging releases with git commits would be very useful

### ISSUE THREAD

**Issue by williammartin** [microservices/omg-cli#109]
I was trying to find out from which commits 0.2.0 and 0.2.1 were built from so that I could `git bisect` the changes to find what introduced #99, but had some trouble. I certainly don't see anything in the git history that would indicate releases. Perhaps there's a way on `npm`?

**Comment by TomPed** [comment]
We will start to make releases here https://github.com/microservices/omg-cli/releases.
