### ISSUE TITLE
Cli microservices are not supported

### ISSUE THREAD

**Issue by Vesuvium** [microservices/omg-cli#115]
Currently cli microservices are not supported, but the documentation describes them as possible option.

In order to work, a `omg run` command would be needed, or the ability to check whether a container is running and switch from exec/run according to the case. 
Arguments should also be passed in the correct format.

**Comment by TomPed** [comment]
@Vesuvium this should be possible. https://github.com/microservice/random is a cli microservice, I believe, and it runs just fine.

**Comment by TomPed** [comment]
I'm going to close this as cli services are supported.
