### ISSUE TITLE
Verbose mode for debugging

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg-cli#118]
A very verbose mode that displays everything that happens would be great. I currently have to debug this:

https://circleci.com/gh/wilzbach/yaml/8

```
> npx omg exec parse -a data="- item"
Exited with code 1
```

(no logs or error message at all).

**Comment by TomPed** [comment]
This was fixed in https://github.com/microservices/omg-cli/pull/133. There is no verbose flag, however logs from docker will be piped to the cli when a failure occurs.
