### ISSUE TITLE
omg build should show more detailed status updates

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg-cli#123]
When the docker build takes a long time, it looks like the command is hanging. Hence, it would be nice if the command could display the current docker command that gets executed, s.t. one knows that it's not hanging.

**Comment by TomPed** [comment]
What do you think about a `--verbose` flag?

**Comment by wilzbach** [comment]
While I would like to have a verbose flag in general, I think showing what's currently happening and that the CLI didn't crash should be the default behavior.

**Comment by Vesuvium** [comment]
Generally one expects software to work or to return a short message on what went wrong. If you can catch errors or detect that something went wrong, you can also show a message like "this thing went wrong, please do this to fix it".

After that you might want to add a verbose or debug flag too.

**Comment by TomPed** [comment]
I mapped out a new pipeline out on how I go about building and executing these services a few days ago. It fixes this issue along with others relating to logs 😄.
