### ISSUE TITLE
Validation fails for valid microservice.yaml

### ISSUE THREAD

**Issue by judepereira** [microservices/omg-cli#139]
For the redis service, validation fails, although the file is valid.
https://github.com/microservice/redis/blob/master/microservice.yml
```
h2:redis jude$ omg validate
Argument: `key` for event: `rpop` has an issue. Events' arguments that interface via http must provide an in
```

**Comment by TomPed** [comment]
I think this is the expected result. You need to provide an `in` for the arguments of an event. [This](https://github.com/microservice/redis/blob/master/microservice.yml#L90) argument should have an `in`.

**Comment by judepereira** [comment]
@TomPed I see - can we improve this error message? It was really unhelpful.

In addition to this, can we provide more helpful error messages for other simple mistakes like this one?

**Comment by TomPed** [comment]
Closing this and making a new issue regarding schema logs.
