### ISSUE TITLE
Provide a --raw flag for exec

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg-cli#148]
```
> omg exec -i yaml format -a "data=[1,2]"
✔ Started Docker container: b0ecd82516d1
✔ Health check passed
✔ Ran action: `format` with output: [
  "--- \"[1,2]\"\n"
]
✔ Stopped Docker container: b0ecd82516d1
```

It would be great to have a `--raw` mode where all logging is suppressed (except for fatal errors of course).

This is useful for testing the microservice output with scripts.

**Comment by TomPed** [comment]
@wilzbach I'm assuming you would want the output of running the command to still output the output right?
