### ISSUE TITLE
OMG execs stops after building the docker image (if the docker image 

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg-cli#149]
https://circleci.com/gh/wilzbach/yaml/18?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Version: 0.5.2

```
> npx omg exec parse -a data="- item"
Sending build context to Docker daemon  10.39MB


Step 1/7 : FROM ruby:2.5-alpine3.8
2.5-alpine3.8: Pulling from library/ruby
cd784148e348: Pulling fs layer
7ac329fc38a6: Pulling fs layer
200e79cbbbd8: Pulling fs layer
b0fbf3acb380: Pulling fs layer
cd784148e348: Verifying Checksum
cd784148e348: Download complete
7ac329fc38a6: Verifying Checksum
7ac329fc38a6: Download complete
200e79cbbbd8: Verifying Checksum
200e79cbbbd8: Download complete
b0fbf3acb380: Verifying Checksum
b0fbf3acb380: Download complete
cd784148e348: Pull complete
7ac329fc38a6: Pull complete
200e79cbbbd8: Pull complete
b0fbf3acb380: Pull complete
Digest: sha256:13b25da163156fbc519147ae35e010ff5b7719f483278dda539e22ff39b04dbb
Status: Downloaded newer image for ruby:2.5-alpine3.8
 ---> b3361f13ff1f
Step 2/7 : RUN mkdir /app
 ---> Running in a7244a83d1a9
 ---> 5dfe35c53c56
Removing intermediate container a7244a83d1a9
Step 3/7 : ADD Gemfile /app
 ---> 50aa2cb1dc11
Step 4/7 : ADD Gemfile.lock /app
 ---> 802048e861d6
Step 5/7 : RUN bundle install --gemfile=/app/Gemfile
 ---> Running in 7994e62b821e
Fetching gem metadata from https://rubygems.org/.........
[...]
Bundle complete! 2 Gemfile dependencies, 15 gems now installed.
Bundled gems are installed into `./usr/local/bundle`
 ---> 3974e35144af
Removing intermediate container 7994e62b821e
Step 6/7 : ADD app.rb /app/app.rb
 ---> ff224806cc63
Step 7/7 : ENTRYPOINT ruby /app/app.rb
 ---> Running in 9dbda94106b3
 ---> 8dc5fa590c96
Removing intermediate container 9dbda94106b3
Successfully built 8dc5fa590c96
Successfully tagged omg/wilzbach/yaml:latest
```

Expected:

```
✔ Built Docker image with name: omg/wilzbach/yaml
✔ Started Docker container: 0ddd9201f700
✔ Health check passed
✔ Ran action: `parse` with output: [
  "item"
]
✔ Stopped Docker container: 0ddd9201f700
```

And not exiting as successful without actually executing the command.

Interestingly enough this works as expected locally (also with Node v11.6.0) (I bumped the [Node version here on the CI](https://circleci.com/gh/wilzbach/yaml/20?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for experimentation).

**Comment by TomPed** [comment]
When the command is ran example: `docker build . -t {tag}` it will exit with error code `0`. And I _think_ the CI will pick that up as the command ran and not actually run the command. This seems to be the issue. I need to see how to get around this.

**Comment by TomPed** [comment]
I think https://github.com/apocas/dockerode might be the solution. Working on this now.

**Comment by judepereira** [comment]
> When the command is ran example: docker build . -t {tag} it will exit with error code 0. And I think the CI will pick that up as the command ran and not actually run the command.

@TomPed I don't think so. This goes against the fundamental design. The parent process hasn't ended. Somehow, the OMG CLI is exiting. It might be worthwhile to put in some verbose logging.

**Comment by TomPed** [comment]
I've found the issue. The issue has to do with https://github.com/sindresorhus/ora.

**Comment by TomPed** [comment]
This might be the fix https://github.com/sindresorhus/ora#stopandpersistoptions.
