### ISSUE TITLE
Define output properties

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#167]
https://github.com/microservices/omg-cli/blob/3dffc7afe1255ce6514c11f25eacb68ecb0a0178/src/schema/schemas/action.ts#L44-L46

`output.properties` has not been defined yet and should be.

**Comment by judepereira** [comment]
@stevepeak There is a spec for defining properties in the OMG. Looks like your issue is only about validating the `properties` object correctly, right?
