### ISSUE TITLE
`omg validate` should output text

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#27]
The `omg validate` command should output text by default that helps the user identify the problem rather than a blog of json (unless requested via `omg validate --json`.

Furthermore, if `omg validate --silent` is used then it should not output any data and only the status code is used as feedback.

**Comment by TomPed** [comment]
@stevepeak for the default action, If the the `microservice.yml` if valid do I just output `Valid`? Also for the case where there are errors, example:
```
{
  "valid": false,
  "issue": {
    "help": "Generates a random boolean",
    "output": null
  },
  "errors": [
    {
      "keyword": "type",
      "dataPath": ".output",
      "schemaPath": "#/properties/output/type",
      "params": {
        "type": "object"
      },
      "message": "should be object"
    }
  ]
}
```
How do we want this to be formatted?

**Comment by stevepeak** [comment]
I think there may be a `ajv.errorsText()` output for you already 😄
