### ISSUE TITLE
Environment from source

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#37]
Add support to pull environment from local source

Before
```sh
omg exec -e FOO=bar -e COLOR=red ...
```

After
```sh
export FOO=bar
export COLOR=red
omg exec -e FOO -e COLOR ...
```

This way you you call the CLI without directly exposing the environment on every call.

**Comment by TomPed** [comment]
Is this possible? I tried to google around and I did not find an easy way to get the env vars set via command line.

**Comment by stevepeak** [comment]
It should work as seen here:

<img width="535" alt="screen shot 2018-07-31 at 13 17 20" src="https://user-images.githubusercontent.com/2041757/43456521-14bb421e-94c4-11e8-8e4f-025973155088.png">

**Comment by TomPed** [comment]
Yeah but that value would still need to get passed at every call because only that process of node would have access to it.

**Comment by stevepeak** [comment]
But in this example I export the variable first and it still works.

<img width="689" alt="screen shot 2018-08-01 at 15 03 23" src="https://user-images.githubusercontent.com/2041757/43523231-0b797da0-959c-11e8-932c-395e05d89c7a.png">
