### ISSUE TITLE
Override connection settings between the docker container and the node server

### ISSUE THREAD

**Issue by judepereira** [microservices/omg-cli#44]
If the Docker host is remote, then the connection between the server spawned by omg locally and the container is broken.

This is because:

1. omg sets OMG_ENDPOINT to point to http://host.docker.internal:${port} : https://github.com/microservices/omg-cli/blob/7b42b957f551afdbdde61ea891d2f314c7890beb/src/commands/Exec.js#L206
2. omg spawns a server which is bound to 127.0.0.1: https://github.com/microservices/omg-cli/blob/7b42b957f551afdbdde61ea891d2f314c7890beb/src/commands/Exec.js#L121

omg needs to accept a new `host` parameter, which will be used in the following two places:

1. the server spawned by omg should bind to this
2. OMG_ENDPOINT must use this as the host

**Comment by TomPed** [comment]
This issue only reguards streaming containers, right?

**Comment by judepereira** [comment]
Yes, that is correct.

**Comment by judepereira** [comment]
Closing since OMG_ENDPOINT is retired.
