### ISSUE TITLE
Undefined "type: object"

### ISSUE THREAD

**Issue by shashanoid** [microservices/omg-cli#98]
Hello, 

It seems like the output **type: object** in the yaml files is not defined. It returns the following error:

<img width="719" alt="screen shot 2018-11-29 at 12 00 11 am" src="https://user-images.githubusercontent.com/5573677/49200512-2a358180-f36b-11e8-8f94-0cb61f9c810e.png">

Seems like the datatype is not defined in the verify.js file. However, changing the output to **type: any** resolves the issue.

**Comment by TomPed** [comment]
@shashanoid I think I just patched this last night in version `0.2.1`. Update your `omg` and you should be good to go. Let me know.

**Comment by shashanoid** [comment]
Hey @TomPed, it's fixed now, just saw another issue raised with build and exec. Version **0.2.0** seems to working !
