### ISSUE TITLE
`build` and `exec` appear to be broken

### ISSUE THREAD

**Issue by williammartin** [microservices/omg-cli#99]
When I run `omg build` or `omg exec` right now I receive the following output:

```
→ omg build
⠙ Building Docker image(node:63942) UnhandledPromiseRejectionWarning: #<Object>
(node:63942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Building Docker image
```

And then stuff seems to generally hang forever.

This was a fresh install of `omg` today.

**Comment by TomPed** [comment]
Hi @williammartin so the current state of the omg with build and exec are this: if there are issue with the docker build throws an error OR if the exec command, which will talk to the docker container, fails the cli will hang and not give any info (the wrong thing to do). Are you able to share your service with me so I can run it and get to the bottom of the issue?

**Comment by williammartin** [comment]
Reverting to 0.2.0 appears to resolve this.

**Comment by TomPed** [comment]
Hmm, okay. I'm look into it now.

**Comment by TomPed** [comment]
@williammartin so I have it building fine on my end:
- Master branch of `williammartin/boyohboy`
- omg version `0.2.1`
- node version `11.1.0`

**Comment by TomPed** [comment]
Cool! I would say update to the LTS which is like `10.14.1` I think.

**Comment by williammartin** [comment]
`6.4.1` was actually the npm version, but I upgraded node to `v11.3.0` and I see the same behaviour.

**Comment by TomPed** [comment]
That's odd, I'm able to build fine. I'll look into it.

**Comment by williammartin** [comment]
`git bisect` determines https://github.com/microservices/omg-cli/commit/c29b02796e6e2c0f9655073490f89b8cdea511de to be the offending commit.

**Comment by TomPed** [comment]
Thanks for the diagnosis! I've made the fix. There are other issues open to take care of the various issues from the docker build command. I'll get on those soon!
